workflows:
  ios-release:
    name: Build iOS Release IPA
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build archive
        script: |
          flutter build ipa --release --no-codesign
      - name: Export IPA
        script: |
          xcrun xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist exportOptions.plist
      - name: Debug export output
        script: |
          ls -R build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
