workflows:
  ios-release:
    name: Build iOS Release IPA
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
      - name: Debug build output
        script: |
          ls -R build/ios
    artifacts:
      - build/ios/ipa/*.ipa
